name: Deploy Website to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'happybirthday'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_951D }}
